version: "3"
services:
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=$NODE_ENV